name: Build and Push anthon-api-2 Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'services/anthon-api-2/**'
      - '.github/workflows/build-anthon-api-image.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build ./packages/anthon-api/ --tag ghcr.io/${{ github.repository }}/anthon-api:latest
          docker push ghcr.io/${{ github.repository }}/anthon-api:latest
